import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Metadata and SEO",
  description: "Generated by create next app",
  openGraph: {
    title: "MyStite Image",
    description: "Open Graph Description",
    url: "https://unsplash.com/photos/cream-sleigh-with-pine-trees-and-pinecones-9V-Ofcxn7IQ",
    siteName: "Example Site",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
